### ISSUE TITLE
speed up distance_matrix

### ISSUE THREAD

**Issue by schlegelp** [vaipatel/morphops#10]
Hi! 

First off: thanks for this library, I'm finding it very useful! I've been using your implementation of thin plate spine transforms and was looking into ways to speed it up. In my case, the bottle neck appears to be [`lmk_util.distance_matrix()`](https://github.com/vaipatel/morphops/blob/e7c4f46142a2ce805a1ffba49c6aab7e01c472e3/morphops/lmk_util.py#L80) which is called in `K_matrix()`. Looking at `distance_matrix()`, I was wondering if you could just use [`scipy.spatial.distance.cdist`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html) instead?

```Python
def distance_matrix(X,Y):
    """For (p1,k)-shaped X and (p2,k)-shaped Y, returns the (p1,p2) matrix 
    where the element at [i,j] is the distance between X[i,:] and Y[j,:].
    """
    return script.spatial.distance.cdist(X, Y)
```

Benchmarking this with `X (16840, 3)` and `Y (26, 3)`, I get ~10s with the current and ~10ms with a scipy implementation of `distance_matrix`.

Best,
Philipp

**Comment by vaipatel** [comment]
Hi there, apologies for the delay.. and thanks for looking into that! I'd left that nested loop in there for too long! It uses `cdist` now.. Thanks again for that suggestion.
